import type { Metadata } from "next";

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://freelance-ayush.vercel.app";

export const metadata: Metadata = {
  title: "Projects | Ayush Kumar — Full Stack & Mobile App Case Studies & Portfolio",
  description:
    "Explore Ayush Kumar's complete portfolio of real-world web and mobile app projects. Detailed case studies on SaaS dashboards, React Native mobile apps, e-commerce platforms, AI integrations, tournament platforms, and attendance management systems.",
  keywords: [
    // ── Core Portfolio Keywords ────────────────────────────────────────────
    "freelance developer portfolio projects",
    "full stack developer case studies",
    "react native app portfolio",
    "nextjs project portfolio 2025",
    "saas dashboard case study",
    "e-commerce project portfolio",
    "ai chatbot project showcase",
    "mobile app portfolio 2025",
    "real world app developer portfolio",
    "startup project development portfolio",
    "live project demo portfolio",
    "ayush kumar projects portfolio",
    "stripe payment integration case study",
    "cms dashboard project showcase",
    "next.js full stack app portfolio",
    "custom ai app case study india",
    "developer project examples 2025",
    "freelance web developer project showcase",
    "react native expo project case study",
    "best developer portfolio india 2025",

    // ── Specific Project Keywords ──────────────────────────────────────────
    "gurugram university attendance system case study",
    "attendance management system portfolio",
    "university software project portfolio",
    "feedo customer feedback app case study",
    "customer feedback platform portfolio",
    "react native feedback app case study",
    "nestjs mongodb case study",
    "jlm tournaments platform case study",
    "online gaming tournament platform portfolio",
    "supabase real-time app case study",
    "music player app case study",
    "react native music app portfolio",
    "expo audio app case study",
    "e-commerce platform case study",
    "nextjs e-commerce case study",
    "stripe integration case study",
    "full-featured online store case study",

    // ── Long-Tail Portfolio Keywords ───────────────────────────────────────
    "ayush kumar case studies",
    "nextjs web app project examples",
    "mobile app developer work samples",
    "real client project case studies india",
    "full stack web app project demos",
    "saas project portfolio india",
    "web development project gallery",
    "portfolio with live apps",
    "software engineer project examples",
    "react developer project case studies",
    "react native developer portfolio india",
    "next.js developer portfolio india",
    "node.js developer portfolio",
    "nestjs developer portfolio",
    "typescript developer portfolio",
    "full stack developer project gallery",
    "mobile developer work samples india",
    "ai integration project portfolio",
    "openai integration case study",
    "supabase project case study",
    "firebase project portfolio",
    "mongodb project portfolio",
    "postgresql project portfolio",
    "socket.io real-time project case study",
    "stripe payment project case study",
    "authentication system case study",
    "admin dashboard project portfolio",
    "crm project portfolio",
    "inventory management project portfolio",

    // ── Hire-Intent Case Study Keywords ───────────────────────────────────
    "hire developer who built saas apps",
    "hire react native developer portfolio",
    "hire nextjs developer portfolio",
    "hire ai integration developer portfolio",
    "hire full stack developer case studies",
    "hire mobile app developer work samples",
    "hire backend developer portfolio",
    "hire node.js developer project examples",
    "hire nestjs developer case study",
    "hire stripe developer portfolio",
    "hire e-commerce developer portfolio",
    "hire tournament platform developer",
    "hire attendance system developer",
    "hire feedback platform developer",
    "hire saas dashboard developer portfolio",
    "hire real-time app developer portfolio",

    // ── Tech-Stack Specific Portfolio ─────────────────────────────────────
    "react 19 portfolio project",
    "next.js 15 portfolio project",
    "react native 0.76 portfolio",
    "expo sdk 52 portfolio",
    "typescript strict project portfolio",
    "nestjs api project portfolio",
    "mongodb atlas project case study",
    "prisma orm project portfolio",
    "trpc project case study",
    "tailwind css portfolio project",
    "framer motion animation portfolio",
    "nativewind mobile portfolio",
    "redux toolkit project portfolio",
    "zustand state management portfolio",
    "clerk auth project portfolio",
    "next-auth project case study",
    "vercel deployment project portfolio",
    "docker project portfolio",
    "aws deployment project portfolio",
    "cloudinary integration portfolio",

    // ── Industry-Specific Portfolio ────────────────────────────────────────
    "education tech project portfolio",
    "gaming platform project portfolio",
    "entertainment app portfolio",
    "feedback and survey app portfolio",
    "university management system portfolio",
    "tournament management app portfolio",
    "music streaming app portfolio",
    "online store project portfolio",
    "payment system project portfolio",
    "real-time communication project portfolio",

    // ── Market / Region Keywords ───────────────────────────────────────────
    "india developer portfolio",
    "indian full stack developer projects",
    "indian react native developer portfolio",
    "best developer portfolio india",
    "top freelance developer portfolio india",
    "indian developer case studies",
    "react developer portfolio usa",
    "react developer portfolio uk",
    "react developer portfolio canada",
    "freelance developer portfolio usa",
    "remote developer portfolio",
    "offshore developer portfolio india",

    // ── Social Proof / Trust Signals ──────────────────────────────────────
    "live project demo links portfolio",
    "open source developer portfolio",
    "github portfolio developer",
    "deployed applications portfolio",
    "production apps developer portfolio",
    "client approved projects portfolio",
    "real world shipped products portfolio",
    "100 percent satisfaction projects",
    "on time delivered projects portfolio",
    "scalable web apps portfolio",
    "performance optimized apps portfolio",
    "seo optimized projects portfolio",
    "accessible web apps portfolio",
    "responsive design project portfolio",
    "mobile-first project portfolio",
    "cross-platform apps portfolio",
    "best ui design project portfolio",
    "clean code project portfolio",
    "well documented projects portfolio",
    "tested applications portfolio",

    // ── Branded Keywords ───────────────────────────────────────────────────
    "ayush kumar full stack portfolio",
    "ayush kumar react native portfolio",
    "ayush kumar nextjs portfolio",
    "ayush kumar node.js portfolio",
    "ayush kumar nestjs portfolio",
    "ayush kumar ai portfolio",
    "ayush kumar saas portfolio",
    "ayush kumar e-commerce portfolio",
    "ayush08k portfolio projects",
    "ayush08k github projects",
    "ayush kumar developer work samples",
    "ayush kumar case study 2025",
    "ayush kumar project showcase 2025",
    "hire ayush kumar portfolio",
    "ayush kumar react developer portfolio",

    // ── SEO for Case Study Pages ───────────────────────────────────────────
    "best freelance developer case study 2025",
    "professional developer portfolio 2025",
    "top rated developer project showcase",
    "award winning developer portfolio",
    "featured developer case studies",
    "in-depth project analysis developer",
    "technical case study web development",
    "technical case study mobile development",
    "deep dive project breakdown developer",
    "architecture overview project showcase",

    // ── 3D & WebGL Project Case Study Keywords (Starbucks 3D) ──────────────────
    "starbucks 3d website case study",
    "react three fiber starbucks customizer",
    "webgl e-commerce project showcase",
    "three.js interactive product portfolio",
    "draco mesh compression case study",
    "3d landing page developer portfolio",
    "webgl mobile performance optimization projects",
    "three.js scroll animation case study",
    "react three fiber shadow baking showcase",
    "interactive 3d product customizer portfolio",
    "creative web development 3d portfolio",
    "three.js canvas memory leak resolution",
    "react 19 three.js project examples",
    "next.js 15 webgl integration projects",
    "three.js product configurator showcase",
    "creative frontend engineer 3d portfolio",
    "draco compressed gltf model gallery",
    "react three fiber adaptive scaling case study",
    "webgl post-processing effects showcase",
    "gsap scrolltrigger 3d camera movements",
    "3d coordinate space web implementation",
    "starbucks 3d cup configurator project",
    "custom materials and shaders portfolio",
    "low-end device webgl fallback case study",
    "3d web assets optimization walkthrough",
    "three.js orbitcontrols custom implementation",
    "three.js custom shader material case study",
    "gltf loader draco compression showcase",
    "interactive 3d store design portfolio",
    "3d e-commerce website development india",
    "three.js freelance project showcase",
    "react three fiber light and shadow setup",
    "3d web animation developer projects",
    "immersive 3d customizer case studies",
    "webgl frame rate optimization 60fps",
    "draco decoder nextjs path configuration",
    "three.js environment maps project example",
    "react three fiber texture loading performance",
    "real-time 3d cup customizer react",
    "3d interactive coffee shop website",
    "gsap timeline with react three fiber",
    "creative developer portfolio 3d design",
    "webgl canvas layout responsiveness",
    "three.js canvas resizing next.js",
    "blender model to react three fiber pipeline",
    "3d web visualizer freelance project",
    "high performance 3d web app case study",
    "react three fiber performance monitoring",
    "mobile friendly 3d interactive websites",
    "3d web product designer portfolio",
  ],
  openGraph: {
    title: "Projects — Ayush Kumar | Full Stack & Mobile App Portfolio & Case Studies",
    description:
      "Detailed case studies and live project demos by Ayush Kumar — SaaS dashboards, React Native mobile apps, AI integrations, e-commerce stores, tournament platforms, and more.",
    url: `${siteUrl}/projects`,
    siteName: "Ayush Kumar — Portfolio",
    images: [
      {
        url: `${siteUrl}/myprofile.png`,
        width: 1200,
        height: 630,
        alt: "Ayush Kumar — Full Stack & Mobile App Projects Portfolio",
        type: "image/png",
      },
    ],
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Projects — Ayush Kumar | Developer Portfolio & Case Studies",
    description:
      "Real-world case studies and live project demos by freelance full stack developer Ayush Kumar. SaaS, mobile apps, AI, e-commerce, and more.",
    images: [`${siteUrl}/myprofile.png`],
    creator: "@Ayush08k",
  },
  alternates: {
    canonical: "/projects",
  },
};
