import type { Metadata } from "next";

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://freelance-ayush.vercel.app";

export const metadata: Metadata = {
  title: "Services | Ayush Kumar — Freelance Full Stack, Mobile App & AI Development Services",
  description:
    "Professional freelance development services by Ayush Kumar. Expert in Next.js, React Native, Node.js, NestJS, AI integrations, SaaS, e-commerce, and custom API development. Affordable rates, world-class quality. Hire today.",
  keywords: [
    // ── Core Service Keywords ──────────────────────────────────────────────
    "full stack development services",
    "web development services",
    "mobile app development services",
    "react native development services",
    "next.js development services",
    "node.js backend development services",
    "typescript development services",
    "ai integration services",
    "saas application development services",
    "e-commerce website development services",
    "landing page development services",
    "api development services",
    "cms integration services",
    "stripe payment integration services",
    "ui ux design and development services",
    "nestjs backend development services",
    "mongodb database development services",
    "postgresql development services",
    "firebase development services",
    "supabase integration services",
    "graphql api development services",
    "websocket real-time development services",
    "socket.io development services",
    "redux toolkit development services",
    "framer motion animation services",
    "tailwind css development services",
    "expo sdk development services",
    "react native expo app services",
    "cross-platform mobile development services",
    "ios android app development services",

    // ── High-Intent Hire Keywords ──────────────────────────────────────────
    "hire freelance developer for services",
    "best web development services india",
    "affordable development services for startups",
    "custom software development services india",
    "freelance full stack services 2025",
    "professional freelance services developer",
    "top rated web development services",
    "web development services for small business",
    "website design and development services india",
    "startup services developer freelance",
    "hire freelance web developer for services",
    "hire react native developer services",
    "hire nextjs developer services",
    "hire node.js backend developer",
    "hire nestjs developer freelance",
    "hire mobile app developer services",
    "hire ai developer services",
    "hire full stack developer services india",
    "hire typescript developer services",
    "hire api developer services",
    "hire stripe integration developer",
    "hire firebase developer services",
    "hire supabase developer services",
    "hire saas developer services",
    "hire mvp developer services",
    "hire e-commerce developer services",
    "hire shopify developer services",
    "hire landing page developer",
    "hire cms developer services",

    // ── Long-Tail Intent Keywords ─────────────────────────────────────────
    "affordable react native developer india services",
    "affordable nextjs developer india services",
    "hire affordable full stack developer india",
    "nestjs api integration freelancer remote",
    "react native expo freelancer services india",
    "nextjs saas developer freelance india",
    "hire freelance backend developer node.js",
    "hire freelance frontend developer react",
    "full stack developer services for startups india",
    "mobile app developer services for startups",
    "ai chatbot integration developer services",
    "openai api integration developer services",
    "llm integration developer services",
    "custom dashboard developer services",
    "real time app developer services",
    "social media app developer services",
    "e-commerce store developer services",
    "shopify store developer services",
    "stripe payment gateway developer services",
    "custom cms developer services",
    "wordpress developer services india",
    "woocommerce developer services india",
    "custom web portal developer services",
    "saas mvp developer services",
    "startup mvp developer services",
    "rapid prototyping developer services",
    "performance optimization developer services",
    "seo optimization developer services",
    "core web vitals optimization services",
    "lighthouse score optimization services",

    // ── Technology-Specific Long-Tails ────────────────────────────────────
    "next.js 15 development services",
    "react 19 development services",
    "react native 0.76 development services",
    "expo sdk 52 development services",
    "typescript strict mode development",
    "nestjs microservices development",
    "prisma orm development services",
    "drizzle orm development services",
    "trpc development services",
    "server side rendering development",
    "static site generation services",
    "edge function development services",
    "vercel deployment services",
    "docker containerization services",
    "aws deployment developer services",
    "ci/cd pipeline setup services",
    "api security implementation services",
    "jwt authentication implementation services",
    "oauth2 integration developer services",
    "clerk auth integration services",
    "next-auth implementation services",
    "socket.io real-time chat development",
    "video call integration developer services",
    "webrtc developer services",
    "push notification developer services",
    "offline sync mobile app services",

    // ── Market-Specific Keywords ──────────────────────────────────────────
    "web development services usa",
    "web development services uk",
    "web development services canada",
    "web development services australia",
    "web development services europe",
    "web development services dubai",
    "web development services singapore",
    "mobile app development services usa",
    "mobile app development services uk",
    "affordable development services usa",
    "affordable development services uk",
    "affordable development services canada",
    "hire freelance developer usa services",
    "hire freelance developer uk services",
    "hire freelance developer canada services",
    "outsource web development india services",
    "outsource mobile development india services",
    "outsource saas development india services",
    "outsource api development india services",
    "remote developer services india",

    // ── Service Pricing & Value Keywords ─────────────────────────────────
    "cheap web development services",
    "cheap mobile app development services",
    "cheap saas development services",
    "affordable web development services",
    "affordable mobile development services",
    "budget friendly development services",
    "low cost web development services",
    "low cost mobile app services",
    "value for money web development services",
    "best price web developer india services",
    "fixed price development services",
    "hourly rate developer services",
    "project based development services",
    "contract developer services",
    "dedicated developer services",

    // ── Project Type Keywords ─────────────────────────────────────────────
    "saas portal development services",
    "admin dashboard development services",
    "crm development services",
    "erp development services",
    "inventory management system services",
    "booking system development services",
    "online marketplace development services",
    "food delivery app development services",
    "ride sharing app development services",
    "fitness app development services",
    "education app development services",
    "healthcare app development services",
    "finance app development services",
    "social media app development services",
    "news app development services",
    "travel app development services",
    "gaming app development services",
    "nft marketplace development services",
    "blockchain integration developer services",
    "defi app development services",

    // ── Quality & Trust Signals ───────────────────────────────────────────
    "top rated freelance development services",
    "5 star rated developer services",
    "verified freelance developer services",
    "professional freelance developer services india",
    "experienced full stack developer services",
    "reliable freelance developer services",
    "on time delivery developer services",
    "clean code developer services",
    "scalable code developer services",
    "secure web development services",
    "responsive web development services",
    "seo friendly web development services",
    "performance optimized development services",
    "well documented code developer services",
    "post-delivery support developer services",
    "free revision developer services",
    "money back guarantee developer services",
    "nda compliant developer services",
    "client focused development services",
    "startup friendly developer services",

    // ── Branded + Personal ────────────────────────────────────────────────
    "ayush kumar development services",
    "ayush kumar web services",
    "ayush kumar mobile services",
    "ayush kumar api services",
    "ayush kumar ai services",
    "ayush kumar saas services",
    "ayush kumar e-commerce services",
    "ayush kumar freelance services",
    "ayush08k development services",
    "hire ayush kumar services",
  ],
  openGraph: {
    title: "Services — Ayush Kumar | Freelance Full Stack, Mobile App & AI Developer",
    description:
      "End-to-end freelance development services: web apps, mobile apps, AI integrations, SaaS portals, e-commerce, APIs, and more. Affordable, reliable, and world-class quality by Ayush Kumar.",
    url: `${siteUrl}/services`,
    siteName: "Freelancer Ayush",
    images: [
      {
        url: `${siteUrl}/myprofile.png`,
        width: 1200,
        height: 630,
        alt: "Ayush Kumar — Freelance Full Stack & Mobile App Development Services",
        type: "image/png",
      },
    ],
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Services — Ayush Kumar | Freelance Full Stack Developer",
    description:
      "Professional freelance web, mobile, and AI development services by Ayush Kumar. Hire today for custom, scalable, affordable software.",
    images: [`${siteUrl}/myprofile.png`],
    creator: "@Ayush08k",
  },
  alternates: {
    canonical: "/services",
  },
};
