import type { Metadata } from "next";

const siteUrl = process.env.NEXT_PUBLIC_SITE_URL || "https://freelance-ayush.vercel.app";

export const metadata: Metadata = {
  title: "Blog | Ayush Kumar — Full Stack Dev Tutorials, Tips & Freelance Insights 2025",
  description:
    "Read expert tutorials, tips, and insights by Ayush Kumar on Next.js, React Native, Node.js, NestJS, TypeScript, AI integrations, SaaS architecture, freelance development, and high-performance web apps.",
  keywords: [
    // ── Core Blog Keywords ─────────────────────────────────────────────────
    "full stack developer blog",
    "next.js tutorial blog",
    "react native developer blog",
    "web development blog india",
    "typescript developer blog",
    "node.js rest api tutorial",
    "freelance developer blog 2025",
    "javascript best practices 2025",
    "mern stack tutorial",
    "expo react native tips",
    "ai integration tutorial",
    "openai api tutorial",
    "build saas app nextjs",
    "best tech stack 2025",
    "freelance tips india developers",
    "web performance optimization tips",
    "how to hire freelance developer",
    "nextjs vs remix comparison",
    "react native vs flutter guide",
    "developer insights india 2025",

    // ── Long-Tail Tutorial Keywords ────────────────────────────────────────
    "how to build a portfolio with nextjs",
    "react native expo tutorial for beginners",
    "how to integrate openai in a web app",
    "best practices for typescript in 2025",
    "full stack project ideas for beginners",
    "freelance developer life blog india",
    "how to get freelance clients india",
    "scaling saas with nodejs",
    "nextjs server actions tutorial",
    "app router nextjs guide 2025",
    "how to optimize nextjs for seo",
    "nextjs 15 new features tutorial",
    "react 19 concurrent features guide",
    "react native 0.76 new architecture guide",
    "expo sdk 52 migration guide",
    "nestjs complete tutorial for beginners",
    "mongodb optimization tips for developers",
    "postgresql vs mongodb comparison 2025",
    "prisma orm tutorial nextjs",
    "drizzle orm tutorial guide",
    "trpc nextjs tutorial step by step",
    "zustand vs redux toolkit comparison",
    "react query vs swr comparison",
    "tailwind css tips and tricks 2025",
    "framer motion animation tutorial",
    "nativewind react native tutorial",
    "expo router tutorial 2025",
    "react navigation v7 guide",
    "clerk authentication nextjs tutorial",
    "next-auth v5 tutorial guide",

    // ── Comparison & Opinion Blogs ─────────────────────────────────────────
    "react native vs flutter 2025 comparison",
    "nextjs vs gatsby 2025 comparison",
    "nextjs vs create react app comparison",
    "nestjs vs express comparison",
    "mongodb vs postgresql comparison 2025",
    "vercel vs netlify comparison 2025",
    "supabase vs firebase comparison 2025",
    "pocketbase vs supabase comparison",
    "expo vs react native cli comparison",
    "typescript vs javascript 2025",
    "bun vs node.js comparison 2025",
    "deno vs node.js comparison",
    "shadcn vs mantine comparison",
    "clerk vs next-auth comparison",
    "stripe vs razorpay comparison india",
    "aws vs vercel comparison developers",
    "docker vs serverless comparison",
    "graphql vs rest api comparison 2025",
    "remix vs nextjs performance comparison",
    "astro vs nextjs comparison",

    // ── Performance & SEO Blog Keywords ───────────────────────────────────
    "how to improve core web vitals nextjs",
    "lighthouse score 100 nextjs tutorial",
    "image optimization nextjs guide",
    "font optimization web performance",
    "javascript bundle size optimization",
    "server side rendering performance tips",
    "static site generation vs server rendering",
    "edge functions performance guide",
    "database query optimization guide",
    "redis caching tutorial nodejs",
    "cdn optimization web performance",
    "lazy loading images react tutorial",
    "code splitting react tutorial",
    "tree shaking javascript guide",
    "web vitals monitoring tutorial",
    "seo optimization nextjs tutorial",
    "structured data schema markup guide",
    "open graph tags tutorial",
    "sitemap generation nextjs guide",
    "robots.txt configuration guide",

    // ── Freelance & Career Keywords ────────────────────────────────────────
    "how to get first freelance client",
    "freelance developer tips india",
    "how to price freelance projects",
    "freelance developer portfolio tips",
    "how to write freelance proposal",
    "best freelance platforms for developers",
    "upwork vs fiverr for developers",
    "how to build freelance reputation",
    "freelance developer income guide india",
    "how to scale freelance business",
    "freelance developer contract tips",
    "remote work tips for developers",
    "how to find remote jobs india",
    "developer interview tips 2025",
    "how to prepare for technical interviews",
    "developer resume tips 2025",
    "github portfolio tips for developers",
    "linkedin optimization for developers",
    "how to grow on twitter as developer",
    "developer personal brand tips",

    // ── AI & Emerging Tech Blogs ───────────────────────────────────────────
    "how to integrate chatgpt in web app",
    "openai api tutorial for developers",
    "langchain tutorial javascript",
    "rag application development tutorial",
    "vector database tutorial pinecone",
    "ai chatbot development tutorial",
    "generative ai web app tutorial",
    "llm integration tutorial nodejs",
    "ai code review tools for developers",
    "github copilot tips for developers",
    "cursor ai tips for developers",
    "prompt engineering guide developers",
    "ai saas application tutorial",
    "ai integration nextjs tutorial",
    "openai function calling tutorial",
    "ai image generation integration tutorial",
    "speech to text integration tutorial",
    "text to speech api tutorial",
    "sentiment analysis integration tutorial",
    "machine learning api integration tutorial",

    // ── Architecture & Best Practices ─────────────────────────────────────
    "clean architecture nodejs tutorial",
    "domain driven design javascript",
    "microservices architecture tutorial",
    "monorepo setup turborepo tutorial",
    "testing best practices javascript",
    "jest unit testing tutorial react",
    "cypress e2e testing tutorial",
    "playwright testing tutorial nextjs",
    "ci/cd pipeline github actions tutorial",
    "docker tutorial for javascript developers",
    "kubernetes introduction developers",
    "api design best practices rest",
    "graphql best practices tutorial",
    "database modeling best practices",
    "authentication security best practices",
    "web security owasp guide developers",
    "rate limiting nodejs tutorial",
    "input validation nodejs tutorial",
    "error handling best practices nodejs",
    "logging best practices nodejs",

    // ── Market-Specific Blog Keywords ─────────────────────────────────────
    "developer blog india",
    "indian developer blog english",
    "developer tutorials in english india",
    "best developer blog 2025",
    "top web development blog 2025",
    "react native blog 2025",
    "nextjs blog 2025",
    "node.js blog 2025",
    "freelance developer blog english india",
    "software engineer blog india 2025",

    // ── Branded & Personal ─────────────────────────────────────────────────
    "ayush kumar developer blog",
    "ayush kumar web development tips",
    "ayush kumar react native tutorials",
    "ayush kumar nextjs tutorials",
    "ayush kumar node.js tutorials",
    "ayush kumar freelance tips",
    "ayush kumar ai tutorials",
    "ayush kumar typescript tips",
    "ayush kumar saas tutorials",
    "ayush08k blog",
    "ayush kumar developer insights",
    "ayush kumar tech blog 2025",
    "ayush kumar programming blog",
    "ayush kumar tutorials 2025",
    "read ayush kumar blog",
  ],
  openGraph: {
    title: "Blog — Ayush Kumar | Full Stack Dev Tutorials, Tips & Freelance Insights",
    description:
      "Expert tutorials, comparisons, tips, and freelance insights by Ayush Kumar. Topics: Next.js, React Native, Node.js, NestJS, TypeScript, AI integrations, SaaS, and developer career growth.",
    url: `${siteUrl}/blog`,
    siteName: "Ayush Kumar — Portfolio",
    images: [
      {
        url: `${siteUrl}/myprofile.png`,
        width: 1200,
        height: 630,
        alt: "Ayush Kumar Developer Blog — Full Stack Dev Tutorials & Freelance Insights",
        type: "image/png",
      },
    ],
    type: "website",
    locale: "en_US",
  },
  twitter: {
    card: "summary_large_image",
    title: "Blog — Ayush Kumar | Full Stack Dev Tutorials & Insights",
    description:
      "Tutorials, tips, and insights from Ayush Kumar on Next.js, React Native, Node.js, AI, SaaS, and freelancing.",
    images: [`${siteUrl}/myprofile.png`],
    creator: "@Ayush08k",
  },
  alternates: {
    canonical: "/blog",
  },
};
